### ISSUE TITLE
Source code, please

### ISSUE THREAD

**Issue by itemkelvin** [boschresearch/neuzzplusplus#1]
Could you please release the source code? When I reproduced the AFL (pure Havoc, without deterministic mutation) and PreFuzz with RTX3090, I found PreFuzz underperformed. I just spent one day running only one program, readelf, but our data are consistent (edge coverage AFL 14k and PreFuzz 13k).

**Comment by ririnicolae** [comment]
@itemkelvin Thanks for your interest in our implementation. It will be available in the upcoming weeks.

**Comment by ririnicolae** [comment]
@itemkelvin Thank you again for your interest. The code is now available. For Prefuzz and our evaluation framework, have a look at the [MLFuzz](https://github.com/boschresearch/mlfuzz) release.
